apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kubernetes-cloudnative-dk
  namespace: default
spec:
  secretName: kubernetes-cloudnative-dk-tls
  issuerRef:
    name: letsencrypt
  commonName: kubernetes.cloudnative.dk
  dnsNames:
  - kubernetes.cloudnative.dk
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - kubernetes.cloudnative.dk
